#!/bin/bash
#PBS -N bwa_mem_C125            
#PBS -P C125_align         
#PBS -l nodes=1:ppn=4,mem=128gb       
#PBS -l walltime=48:00:00             
#PBS -o bwa_output.log                
#PBS -e bwa_error.log  
#PBS -M 28770420@sun.ac.za
#PBS -m abe
#PBS -P HEAL1360               

module load chpc/BIOMODULES
module load bwa
module load samtools


cd $PBS_O_WORKDIR

REF="$PBS_O_WORKDIR/Liger/Liger_ref.fasta"
R1="$PBS_O_WORKDIR/C125_1.fq.gz"
R2="$PBS_O_WORKDIR/C125_2.fq.gz"
OUTSAM="$PBS_O_WORKDIR/C125_aligned.sam"
OUTBAM="$PBS_O_WORKDIR/C125_sortedLiger.bam"


bwa mem -t 4 $REF $R1 $R2 > $OUTSAM


samtools view -@ 4 -Sb $OUTSAM | samtools sort -@ 4 -o $OUTBAM


samtools index $OUTBAM

echo " Alignment complete: $OUTBAM and index ready."
